### ISSUE TITLE
Apply the model on a interactive art demo

### ISSUE THREAD

**Issue by HarryGuan22** [edstoica/lucid_stylegan3_datasets_models#1]
Thank you so much for sharing your artistic model to the community. I'm a media art student new to machine learning. I'm currently apply your 'yellow comic alien 004 kimg' model on a interactive art demo. It looks pretty cool and I'm really appriciate your time and effort! 
Here is a video preview: https://youtu.be/lVJnj5PLghs

**Comment by edstoica** [comment]
hey harry,
thanks for the message.
so cool to see other people using the datasets and models.
thanks also to include the link in you video description 👍 

your idea is really funny. may you explain to me: how does posenet interact with the model?

**Comment by HarryGuan22** [comment]
It's very nice to hear from you.
I just set up OSC communication between visualizer.py and the ml5.js
PoseNet.
In visualizer.py, I integrate python.osc to make it available to receive
information via OSC(open sound control) in real-time.
And then I apply osc.js to send ml5.js PoseNet captured data to the
specific OSC port.
On the visualizer.py side, there is a dragging behavior to walk through the
latent space. I just replaced the changing mouse position (dx,dy) with the
OSC data from ml5.js PoseNet.
Also, you can do something to other parameters like Truncate.
Hope this helps!


lucid layers ***@***.***> 于2022年2月21日周一 10:12写道：
